[project]
name = "tinyvec"
version = "0.1.0"
description = ""
authors = [
    {name = "tylerpuig"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy (>=2.2.3,<3.0.0)",
    "setuptools (>=75.8.0,<76.0.0)",
    "wheel (>=0.45.1,<0.46.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0", "setuptools>=75.8.0", "wheel>=0.45.1"]
build-backend = "setuptools.build_meta"
[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pytest-asyncio = "^0.25.3"

