name: Build Packages Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_package:
    name: Build package on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy build setuptools wheel

      # Build extension modules first
      - name: Build extensions
        working-directory: ./bindings/python
        run: python setup.py build_ext

      # Use build to create both wheel and sdist
      - name: Build package on ${{ matrix.os }} Python ${{ matrix.python-version }}
        working-directory: ./bindings/python
        run: python -m build

      # Upload built packages as artifacts
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: tinyvec-${{ matrix.os }}-py${{ matrix.python-version }}
          path: ./bindings/python/dist/*
          retention-days: 14
  combine_artifacts:
    name: Combine all artifacts
    needs: build_package
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: combined-artifacts

      - name: Create combined zip
        run: |
          cd combined-artifacts
          zip -r ../tinyvec-all-packages.zip ./*

      - name: Upload combined zip
        uses: actions/upload-artifact@v4
        with:
          name: tinyvec-all-packages
          path: tinyvec-all-packages.zip
          retention-days: 14
