name: Build Wheels for Testing

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]
  # Allow manual trigger from the Actions tab
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        # Python package subfolder
        working-directory: ./bindings/python
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.5

      - name: Debug package structure
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          echo "Package structure:"
          find . -type f -name "*.py" | grep -v "__pycache__" || echo "No Python files found"

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp311-*" # Only build for Python 3.11
          CIBW_ARCHS_MACOS: "x86_64 arm64" # Build for both Intel and M1 Macs
          CIBW_BEFORE_BUILD: "pip install setuptools wheel numpy"
          CIBW_SKIP: "pp* *musllinux*"
          CIBW_ENVIRONMENT: "SETUPTOOLS_SCM_PRETEND_VERSION=0.1.0"

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./bindings/python/wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    defaults:
      run:
        # Set the working directory to the Python package subfolder
        working-directory: ./bindings/python
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: python -m pip install build wheel setuptools

      - name: Build sdist
        run: python -m build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: ./bindings/python/dist/*.tar.gz
