name: Build Python Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_package:
    name: Build package on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy build setuptools wheel

      # Set up system dependencies for Linux
      - name: Set up system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ make

      - name: Configure macOS for universal2 build
        if: runner.os == 'macOS'
        run: |
          echo "MACOS_UNIVERSAL=true" >> $GITHUB_ENV

      # Build extension modules first
      - name: Build extensions
        working-directory: ./bindings/python
        run: python setup.py build_ext

      # Use build to create both wheel and sdist
      - name: Build package
        working-directory: ./bindings/python
        run: python -m build

      # Upload built packages as artifacts
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.os }}
          path: ./bindings/python/dist/*
          retention-days: 14
